AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'examples/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
Metrics/LineLength:
  Max: 100
Style/GlobalVars:
  AllowedVariables: [$RSPEC_TEST]
Style/MultilineOperationIndentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20