notifications:
  email: false
language: objective-c 
rvm:
  - 2.0
  - 2.1
  - 2.2
before_install:
  - brew update
  - brew install pdflib-lite
  - brew install gnuplot --with-png
  - bundle install
install:
  - bundle exec rake install
script:
  - bundle exec rake spec
